### ISSUE TITLE
cannot find module issue ts(2307).

### ISSUE THREAD

**Issue by PrathameshChari04** [cyela/Angular-Springboot#1]
Hello Sir,
              I am Facing a error while importing the models and service in other components. I have checked all the directory properly but still i am facing such error it would be great full if u provide a valueable solution to my problem. Hoping for  a positive response.
![Untitled](https://user-images.githubusercontent.com/34868352/59419323-50db7700-8de8-11e9-8e7b-5bf32c9400cb.png)

**Comment by cyela** [comment]
Hi,
sorry for delay response. Can you please delete line 3 and 4, try to import the models again through visual studio suggestion
